### PR TITLE
Frosted navbar

### PR DESCRIPTION
**Pull request by Akash1965**
### Changes
I have added  background-color: rgba(255, 255, 255, .15); -webkit-backdrop-filter: blur(5px); backdrop-filter: blur(5px); to .navbar class and removed the .bg-dark-subtle because the .bg-dark-subtle class was overriding the  background-color: rgba(255, 255, 255, .15) css

### CODE REVIEW

**Review by arpittyagirocks — CHANGES_REQUESTED** [review]
Hello, thank you for contributing
this looks amazing, but i would like some changes :
- [ ]  add some color with the blur effect as the Header title and cart logo are in white color and their visiblity decreases when scrolling over any white color
- [ ]  also remove the border from the navbar

**Comment by Akash1965** [comment]
### Changes
Removed `border` and `border-dark` classes and changed the bg-color of navbar

**Review by arpittyagirocks — CHANGES_REQUESTED** [review]
Awesome job !! 👏
just some final changes 
- [ ] make the search bar placeholder, search bar bottom border to be White
- [ ] and increase the opacity of navbar background to 0.4

+ and i will merge the pull request, give it a star if you like the website

**Comment by Akash1965** [comment]
### Changes
Changed searchbar placeholder and bottom border to white.
Increased blur effect of navbar.

Let me know if there's any modifications if required

**Review by arpittyagirocks — APPROVED** [review]

**Pull request merged**
