### PR TITLE
payments option's issue solved

### PR DESCRIPTION
**Pull request by Pulkitxm**
cod and online payments options
image
image

paymets options
image

### CODE REVIEW

**Review by arpittyagirocks — CHANGES_REQUESTED** [review]
Actually what i really wanted is an actual payement gateway which means user should be actually able to pay to the website using APIs.
but this pull request is a good add on too
See the sequence is 
`information` => `Shipping` => `payment`
- In your changes on shipping page when we chose shipping method, it shows pay now button, instead of going to the payment page
- also make it responsive

**Comment by Pulkitxm** [comment]
Have a look at it I had removed the payment option displayed at shipping page and for the API n all you can refer to [https://nordicapis.com/10-payment-apis/](https://nordicapis.com/10-payment-apis/) , these might require payment procedures so you can explore it

**Review by arpittyagirocks — CHANGES_REQUESTED** [review]
@Pulkitxm, Hey ! Thank you ...
just make the checkout responsive and i will merge the pull request

**Comment by Pulkitxm** [comment]
you can merge it now

**Review by arpittyagirocks — COMMENTED** [review]
Have a look at deploy preview of this pull request...
https://deploy-preview-23--humaridukan.netlify.app/

how can i merge it .... ?

**Comment by Pulkitxm** [comment]
Hello @arpittyagirocks , I tried my best to make the resposiveness in the pull request, but I'm facing difficulties in implementing them as requested. I kindly request you to consider merging the changes that have already been made , as I have reverted back the wrong responsive behaviour . Thank you for your understanding.

**Review by arpittyagirocks — APPROVED** [review]
Thank you for your contribution !

**Pull request merged**
